name: pnpm workspace deploy

# trigger on push to main instead of github release as trigger for the action
on:
  pull_request:
    branches:
      - main

    # TODO: dynamically add the paths using the software-tool-automation
    paths:
      - 'packages/**'
      - 'utils/**'
      
  workflow_dispatch:  # Add this line to enable manual triggering

# prevent concurrent runs of this workflow on the same branch
concurrency: ${{ github.workflow }}-${{ github.ref }}

# see https://pnpm.io/continuous-integration#github-actions
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # setup pnpm using the version from the packageManager property
    # see https://github.com/pnpm/action-setup?tab=readme-ov-file#install-only-pnpm-with-packagemanager

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        # version is pulled from packageManager property in package.json
        # version: ...

        # we will be caching node and then install dependencies
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        # node version will come from the package.json file
        # node-version: ...
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install        


    # # run tests only on the code that has changed
    # # - name: Run tests
    # #   run: pnpm test:changed

    # # verify that the code is formatted correctly and fail
    # # - name: Run Prettier check
    # #   run: pnpm prettier:check

    # - name: bump versions and commit
    #   run: pnpm release:first
