name: pnpm workspace deploy

# trigger on push to main instead of github release as trigger for the action
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual triggering

# see https://pnpm.io/continuous-integration#github-actions
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:

    # setup pnpm using the version from the packageManager property
    # in package.json (see https://github.com/pnpm/action-setup?tab=readme-ov-file#install-only-pnpm-with-packagemanager
    
    # - uses: actions/checkout@v4
    # - name: Install pnpm
    #   uses: pnpm/action-setup@v4

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'pnpm'
    # - name: Install dependencies
    #   run: pnpm install

    # # run tests only on the code that has changed
    # # - name: Run tests
    # #   run: pnpm test:changed

    # # verify that the code is formatted correctly and fail
    # # - name: Run Prettier check
    # #   run: pnpm prettier:check

    # - name: bump versions and commit
    #   run: pnpm release:first
