name: Bump versions and update CHANGELOG.md after PR approval

on:
  pull_request_review:
    types: [submitted]

  # enable manual triggering
  workflow_dispatch:


jobs:
  run_on_approval:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository from github
    # see https://github.com/actions/checkout
    uses: actions/checkout@v4

