name: On pull request approved - bump versions and update CHANGELOG.md

on:
  pull_request_review:
    types: [submitted]

  # enable manual triggering
  workflow_dispatch:


jobs:
  run_on_approval:
    if: github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository from github
      # see https://github.com/actions/checkout
      uses: actions/checkout@v4

    - name: Exit if the branch is not staging.
      run: |
        if [[ "$BRANCH_NAME" != "staging" ]]; then
          echo "Not the staging branch. Exiting."
          exit 0
        fi

    - name: Install package manager pnpm
      # see https://github.com/pnpm/action-setup
      uses: pnpm/action-setup@v4
      with:
        # version is pulled from packageManager property in package.json
        # version: ...

        # we will be caching node and then install dependencies
        run_install: false

    - name: Install Node.js
      # see https://github.com/actions/setup-node
      # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md
      uses: actions/setup-node@v4
      with:
        # node version will come from the package.json file
        # node-version: ...
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install        


    - name: Bumping all changed package versions and updating CHANGELOG.md
      run: pnpm release

    - name: Pushing changes to the repository
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "chore(release): bump versions and update changelog after approval"
        git push
